@host = https://localhost
@port = 7178
@token = CfDJ8DA_vqotUxJFklS7N397sbGW6vN0FaiTslZjwfEc73JMhncAX8QcBKlHFL4UY720xQwZ2sfq40RpvUHV1Maz_r247ADa4o1EetAucVhbBpn2AzfaQKo-mfHuu8tZB58p6NAZa98QfGC9qG96Xo-QlUuMHrCS0HXmq_G8di1u_PSpORRXhjvg-Pz94FVMffDANn647w5ZsP1kpFOxFD-RZ6Igbh_xGOuBVEzmItQRqtX8vwWyY0lFUFQLnEfDFCSuYyEmYEDNlw9rolTvubxGP4k-F8r1hJ1kTZyIKtHaXvwae8ajumqKfoUDl4_fqVGRO_oxAxG1zdsJe5reSOX5GyBj45GF5ymEx8ikJWpibnA9vKg0VXxVaA0huDrole-GwFT8harD1lHvp_BEONs7dk0NF325kxyY_OvUL0dFzCkIp5WrUpGMIAjBapUpSjSBaBdCw8rUbQ-Q-1gD3svSyV9nDK734UEXpArR09uoNNla-KELl_QXJjLGONDlmR-AJ2TqY9p7X5vUivLe4c3rDckgC1Lj-LNiqtFEDMrUpcyWg7kv0zpMuZWEbhaAqsqVx5t5MF-UmT9UyR1Gvtoq9bOw2Pj-xtW1BLIFNXZEDDRPJiqQHDIGI3BPpyezGg-AO5snLrOcUzpQLBurEnHVpW3b63kVoKWAs_j51UGgNY13O2zt9VK16x2_FjRR60t6pg18LDx3KJj7otuWfucf_KpkCRdTskmmWwdVB_yYl_-KE00hIFeX5T-YX5iv5uF6TtQPOT55oy7INiMmDBtakLatzpDDpon2CTAQIb72J-9i

@Restaurants.API_HostAddress = https://localhost:7178


GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=30&pageNumber=2
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "YOLO",
    "Description": "Fit kebab",
    "Category": "Polish",
    "HasDelivery": true,
    "ContactEmail": "sample@mail.com",
    "ContactNumber": "123-321-4567",
    "City": "Gdañsk",
    "Street": "Pyszna 1",
    "PostalCode": "80-910"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "BBQ ribs",
  "Description": "In American cuisine, ribs usually refers to barbecue pork ribs, or sometimes beef ribs, which are served with various barbecue sauces.",
  "Price": 20.99,
  "KiloCalories": 900
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/

###

GET https://localhost:7178/api/restaurants/1/dishes/4

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "SUPER KING",
    "Description": "A very best kebab in the town",
    "HasDelivery": true
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4
Authorization: Bearer {{token}}

###
