@host = https://localhost
@port = 7178
@token = CfDJ8DA_vqotUxJFklS7N397sbFV2PxcuI7c6zivSozQ3a5Q_e1pbFIhsJfhLb9nYgHoZprCndjDIbSMbFVcsCbwtvuawq_IEeoxFFueAQ23UQ5r7DwXHHjmy1s_dXJq5AXFw1SltgsJcgo0DiCyNPUbK7pPd

@Restaurants.API_HostAddress = https://localhost:7178


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "Name": "Kebab King",
    "Description": "A best kebab in the town",
    "Category": "Polish",
    "HasDelivery": true,
    "ContactEmail": "kebab@king.com",
    "ContactNumber": "123-321-4567",
    "City": "Olsztyn",
    "Street": "Najlepsza 1",
    "PostalCode": "78-910"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "BBQ ribs",
  "Description": "In American cuisine, ribs usually refers to barbecue pork ribs, or sometimes beef ribs, which are served with various barbecue sauces.",
  "Price": 20.99,
  "KiloCalories": 900
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/

###

GET https://localhost:7178/api/restaurants/1/dishes/4

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}